//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectReferenceValidator.Lib.Tests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleProjectFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleProjectFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectReferenceValidator.Lib.Tests.TestData.ExampleProjectFiles", typeof(ExampleProjectFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk.WindowsDesktop&quot;&gt;
        ///
        ///    &lt;PropertyGroup&gt;
        ///        &lt;OutputType&gt;WinExe&lt;/OutputType&gt;
        ///        &lt;TargetFramework&gt;netcoreapp3.1&lt;/TargetFramework&gt;
        ///        &lt;UseWPF&gt;true&lt;/UseWPF&gt;
        ///        &lt;AssemblyVersion&gt;1.2.0.0&lt;/AssemblyVersion&gt;
        ///        &lt;FileVersion&gt;1.2.0.0&lt;/FileVersion&gt;
        ///    &lt;/PropertyGroup&gt;
        ///
        ///    &lt;ItemGroup&gt;
        ///        &lt;None Remove=&quot;FaigleSolutions.png&quot; /&gt;
        ///    &lt;/ItemGroup&gt;
        ///
        ///    &lt;ItemGroup&gt;
        ///        &lt;PackageReference Include=&quot;Ookii.Dialogs.Wpf.NETCore&quot; Version=&quot;2.0.0&quot; /&gt;
        ///    &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoProjectReferences {
            get {
                return ResourceManager.GetString("NoProjectReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Sdk=&quot;Microsoft.NET.Sdk.WindowsDesktop&quot;&gt;
        ///
        ///  &lt;PropertyGroup&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputType&gt;
        ///    &lt;TargetFramework&gt;netcoreapp3.1&lt;/TargetFramework&gt;
        ///    &lt;UseWPF&gt;true&lt;/UseWPF&gt;
        ///    &lt;AssemblyVersion&gt;1.2.0.0&lt;/AssemblyVersion&gt;
        ///    &lt;FileVersion&gt;1.2.0.0&lt;/FileVersion&gt;
        ///  &lt;/PropertyGroup&gt;
        ///
        ///  &lt;ItemGroup&gt;
        ///    &lt;None Remove=&quot;FaigleSolutions.png&quot; /&gt;
        ///  &lt;/ItemGroup&gt;
        ///
        ///  &lt;ItemGroup&gt;
        ///    &lt;PackageReference Include=&quot;Ookii.Dialogs.Wpf.NETCore&quot; Version=&quot;2.0.0&quot; /&gt;
        ///  &lt;/ItemGroup&gt;
        ///
        ///  &lt;ItemGroup&gt;
        ///    &lt;Projec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProjectReferenceAndOtherItems {
            get {
                return ResourceManager.GetString("ProjectReferenceAndOtherItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;15.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///    &lt;Import Project=&quot;..\packages\MSTest.TestAdapter.2.1.2\build\net45\MSTest.TestAdapter.props&quot; Condition=&quot;Exists(&apos;..\packages\MSTest.TestAdapter.2.1.2\build\net45\MSTest.TestAdapter.props&apos;)&quot; /&gt;
        ///    &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ThreeProjectReferencesAndOtherItems {
            get {
                return ResourceManager.GetString("ThreeProjectReferencesAndOtherItems", resourceCulture);
            }
        }
    }
}
